version: "3.9"
services:
  db:
    container_name: mongo-mockup
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # - ./data/db:/data/db # Uncomment if you want this to save db state in local too.
    env_file:
      - .env